init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - /tmp/e2e/mlyc -m fli -a 'fl|float32:1.00054;sl:a'
      - /tmp/e2e/mlyc -m fli -a 'fl|float32:1.00053;sl:a'
      - /tmp/e2e/mlyc -m fli -a 'fl|float32:1.20001;sl:a'
      - /tmp/e2e/mlyc -m fli -a 'fl|float32:1.2,1.5;sl:a,b'
      - /tmp/e2e/mlyc -m flinc -a 'fl|float32:1.2;sl:a'

  assert:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
    actual: $actual
    expect: $L