init:

pipeline:

  datastore:
    description: start datly app with rule generted from SQLs
    action: run
    request: '@datastore'

  app:
    description: start datly app with rule generted from SQLs
    action: run
    request: '@app'

  test:
    tag: $pathMatch
    descriptio